Allow to use PKCE
fsinfuhh/py_simple_openid_connect pull request #23
Opened 2024-08-21 09:54 UTC by sbrunner

Proof Key for Code Exchange
Defined by RFC7636
https://www.rfc-editor.org/rfc/rfc7636

2024-08-22 14:26 UTC, ftsell requested changes
Thanks for contributing!

Are you willing to work on this more or is this more of a pointer to what's missing and how to implement it?

I have not tested this PR in depth but the added functionality is definitely a good thing to have.
A few things though:
- I have marked two sections of code with some minor details. Please address those.
- I would very much like to document this a bit better. This could be as an example in the documentations [Usage Section](https://simple-openid-connect.readthedocs.io/en/stable/usage.html) or as part of the docstrings.
- In your PR description you use `pkce.generate_pkce_pair()`. Even though generating pkce pairs is not very complex, I would like to provide that functionality as part of this library. So if you've implemented that part already, please commit the `pkce.py` file.

2024-08-22 14:26 UTC, ftsell commented on src/simple_openid_connect/data.py
> +import code
This is probably left over from debugging

2024-08-22 14:26 UTC, ftsell commented on src/simple_openid_connect/data.py
> +    "OPTIONAL. Code Challenge Method Code challenge method used in the code challenge. If the code_challenge is present, this parameter is REQUIRED."
> Code Challenge Code challenge used in the code challenge

While I realize how one can come up with these word combinations, it is a bit too much spaghetti for my taste.
A rewording of the docstring would be appropriate.

2024-09-08 19:39 UTC, ftsell commented
> Thanks for the review, updated :-) The pkce code comes from this package: [pypi.org/project/pkce](https://pypi.org/project/pkce/) It's true that's relay simple, but I'm not sure that good to copy this code, other proposition it to add it as a dependency or an extra dependency, what do you want me to do?

I'm not really a fan of micro-packages so I would prefer copying the relevant PKCE code over into our source tree

2024-09-09 06:37 UTC, sbrunner commented
@ftsell done :-)

2024-09-23 13:57 UTC, ftsell approved these changes
Thanks. Especially for mentioning where the pkce code was taken from.
I'd eventually like to also add tests and convert the pkce docstrings to our format but for now we can merge this PR if you want

2024-09-30 10:47 UTC, merged